# Generated by Django 2.2.14 on 2024-06-23 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wehrehouse',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrocliente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mercancia',
            name='regisro_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.RegistroCliente', verbose_name='registro cliente'),
        ),
        migrations.AddField(
            model_name='mercancia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dirrecion',
            name='regisro_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.RegistroCliente', verbose_name='registro cliente'),
        ),
    ]
